"""Loggout table

Revision ID: 24adf5838fd3
Revises: 2cceb26436cf
Create Date: 2025-01-23 15:03:04.870813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24adf5838fd3'
down_revision = '2cceb26436cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens'))
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_jti'))

    op.drop_table('tokens')
    # ### end Alembic commands ###
