"""empty message

Revision ID: ab19b5a438e8
Revises: dfcd30f32a4b
Create Date: 2025-01-07 08:11:23.689131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab19b5a438e8'
down_revision = 'dfcd30f32a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actives', schema=None) as batch_op:
        batch_op.drop_constraint('fk_actives_user_id_members', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_actives_user_id_payments'), 'payments', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_actives_user_id_payments'), type_='foreignkey')
        batch_op.create_foreign_key('fk_actives_user_id_members', 'members', ['user_id'], ['id'])

    # ### end Alembic commands ###
