"""empty message

Revision ID: eb4446cfc3ca
Revises: ea61a3b566bd
Create Date: 2025-01-06 17:45:36.870792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4446cfc3ca'
down_revision = 'ea61a3b566bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_payments_transaction_id'), ['transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payments_transaction_id'), type_='unique')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
