"""empty message

Revision ID: f7326f0f9025
Revises: 1ba66b36a14f
Create Date: 2025-01-23 16:34:33.052524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7326f0f9025'
down_revision = '1ba66b36a14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens'))
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_tokens_jti')

    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_tokens')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index('ix_tokens_jti', ['jti'], unique=False)

    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
